// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _3F3R.Models;

namespace _3F3R.Migrations
{
    [DbContext(typeof(_3F3RContext))]
    partial class _3F3RContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("_3F3R.Models.Puesto", b =>
                {
                    b.Property<int>("CP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitud")
                        .HasColumnType("REAL");

                    b.Property<string>("Localidad")
                        .HasColumnType("TEXT");

                    b.Property<double>("Longitud")
                        .HasColumnType("REAL");

                    b.Property<string>("Plaza")
                        .HasColumnType("TEXT");

                    b.HasKey("CP");

                    b.ToTable("Puestos");
                });

            modelBuilder.Entity("_3F3R.Models.Usuario", b =>
                {
                    b.Property<string>("Mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Mail");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("_3F3R.Models.Zona", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Coordenadas")
                        .HasColumnType("REAL");

                    b.Property<int?>("PuestoCercanoCP")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("PuestoCercanoCP");

                    b.ToTable("Zonas");
                });

            modelBuilder.Entity("_3F3R.Models.Zona", b =>
                {
                    b.HasOne("_3F3R.Models.Puesto", "PuestoCercano")
                        .WithMany()
                        .HasForeignKey("PuestoCercanoCP");

                    b.Navigation("PuestoCercano");
                });
#pragma warning restore 612, 618
        }
    }
}
