// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _3F3R.Models;

namespace _3F3R.Migrations
{
    [DbContext(typeof(_3F3RContext))]
    partial class _3F3RContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("_3F3R.Models.Puesto", b =>
                {
                    b.Property<int>("CP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Altura")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Calle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Horarios")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plaza")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CP");

                    b.ToTable("Puestos");
                });

            modelBuilder.Entity("_3F3R.Models.Zona", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Calle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Localidad")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PuestoCP")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("PuestoCP");

                    b.ToTable("Zonas");
                });

            modelBuilder.Entity("_3F3R.Models.Zona", b =>
                {
                    b.HasOne("_3F3R.Models.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("PuestoCP");

                    b.Navigation("Puesto");
                });
#pragma warning restore 612, 618
        }
    }
}
